rootProject.name = "mathsets-kt"

include(":kernel")
include(":logic")
include(":set")
include(":relation")
include(":function")
include(":construction")
include(":ordinal")
include(":cardinal")
include(":descriptive")
include(":combinatorics")
include(":forcing")
include(":examples")
include(":algebra")
include(":polynomial")
include(":category")
include(":galois")
include(":typetheory")
include(":computability")
include(":modeltheory")
